### ISSUE TITLE
Support for Comments: Auto-Removal, Block Comments, and Shortcut Failures

### ISSUE THREAD

**Issue by zarifpour** [zed-industries/extensions#1002]
### Check for existing issues

- [X] Completed

### Misc notes

Regarding this issue reported for Solidity: https://github.com/zarifpour/zed-solidity/issues/7

I have encountered a number of issues trying to resolve this.

---

### Issue 1: Comments are automatically removed

Here I press ⌘/ on one line then ⌘S to save. The comment is automatically removed.

![CleanShot 2024-07-05 at 20 08 31 on Zed — example sol — zed-solidity](https://github.com/zed-industries/extensions/assets/16494335/902438ce-c7a2-4d38-a497-b10657abfd40)

---

### Issue 2: Block comments are always used

As seen above, I only had my cursor on one line, but a block comment is automatically used. Even on an empty line when I hit the shortcut for toggle comment `/**/` is always preferred over `//`.

---

### Issue 3: When block comment is removed from `config.toml`, the toggle comment shortcut doesn't work

[The reporter suggested removing `block_comment` entirely as a fix.](https://github.com/zarifpour/zed-solidity/issues/7#issuecomment-2207957822) However, on my machine, when this is removed, support for using the shortcut is entirely broken.

---

Is there any documentation around this? I am not sure if it's a problem with my local Zed config or with the extension.

**Comment by brockelmore** [comment]
`line_comment` should be `line_comments` by the way. So config.toml is 
```toml
name = "Solidity"
grammar = "solidity"
path_suffixes = ["sol"]
autoclose_before = ";:.,=}])>"
line_comments = ["// ", "/// "]
# block_comment = ["/*", "*/"]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
]
```
