### ISSUE TITLE
Language: Factor

### ISSUE THREAD

**Issue by AndydeCleyre** [zed-industries/extensions#1135]
### Check for existing issues

- [X] Completed

### Language

Factor

### Misc notes

Homepage: https://factorcode.org/

Existing syntax definitions, though some outdated and none necessarily perfect:

- https://github.com/pygments/pygments/blob/master/pygments/lexers/factor.py
- https://gitlab.com/saalen/highlight/-/blob/master/langDefs/factor.lang
- https://github.com/rkoeninger/sublime-factor/blob/master/Factor.sublime-syntax
- https://github.com/DexterHaslem/vscode-factor/blob/master/syntaxes/Factor.tmLanguage

**Comment by AndydeCleyre** [comment]
Here's a simple syntax definition, for the micro editor, but I can't remember where I found it:

`factor.yaml`:

```yaml
filetype: factor

detect:
    filename: "\\.factor$"

rules:
    - identifier: "\\b[A-Za-z_0-9-]*\\b"

    - statement: "\\b(?i:(if|else|then|do|loop|case|endcase|of|endof|begin|while|repeat|until|again|unloop|leave|exit|done|next|\\?do|\\+do|\\-do|\\+loop|\\-loop|\\?leave))\\b"

    - statement: "(^:|;$)"

    - type: "\\b(?i:(variable|constant|cells))\\b"

    - special: "\\B[?.]\\B" #for some reason, \b and \B are inverted for symbols

    - constant.number: "\\b[0-9]+\\b"

    - constant.string:
        start: "\\b([Ss.]\" )"
        end: "\""
        rules: []

    - comment:
        start: "\\("
        end: "\\)"
        rules:
            - todo: "(TODO|NOTE|XXX|FIXME):?"

    - comment:
        start: "\\!"
        end: "$"
        rules:
            - todo: "(TODO|NOTE|XXX|FIXME):?"
```
