### ISSUE TITLE
Kubernetes support and autocompletion

### ISSUE THREAD

**Issue by nicraMarcin** [zed-industries/extensions#1535]
### Check for existing issues

- [X] Completed

### Describe the feature

I'd like to ust zed with kubernetes but it doesn't show any autocompletions. 
How to add kubernetes support?

### If applicable, add mockups / screenshots to help present your vision of the feature

![Zrzut ekranu 2024-10-16 o 17 04 54](https://github.com/user-attachments/assets/c930f6ed-05fc-469c-929f-e5a995e8f530)

**Comment by mattmess1221** [comment]
Using the yaml-language-server with a $schema comment pointing to the swagger.json seems to work well enough for me, though it's not as good as the vscode kubernetes tools extension where it can auto choose the spec based on the apiVersion and kind.

```yaml
# yaml-language-server: $schema=https://github.com/kubernetes/kubernetes/raw/refs/heads/master/api/openapi-spec/swagger.json#/definitions/io.k8s.api.apps.v1.Deployment
apiVersion: app/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx
  template:
    spec:
      metadata:
        labels:
          app: nginx
      containers:
        - name: nginx
          image: nginx

```

Alternative schema, one used by kubeconform
```yaml
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/master/deployment.json
```

Or with strict keys:

```yaml
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/master-standalone-strict/deployment.json
```
