### ISSUE TITLE
TODO/FIXME highlighting

### ISSUE THREAD

**Issue by TENX-S** [zed-industries/extensions#523]
### Check for existing issues

- [X] Completed

I think it's a common and useful feature, since the mainstream editors (IDEA, VS Code) all support it.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="249" alt="image" src="https://user-images.githubusercontent.com/40336192/211147835-726fb45f-310d-4436-bd6b-39931d99ef4b.png">

**Comment by krstp** [comment]
FYI: I put the comment on https://github.com/zed-industries/zed/issues/6013, but dos not seem this feature is implemented in latest releases.

**Comment by krstp** [comment]
This is not merged yet, correct?

**Comment by JosephTLyons** [comment]
> My experiment, it worked:
> 
> <img alt="image" width="852" src="https://private-user-images.githubusercontent.com/45585937/311336184-0ac0df7e-01f2-4270-b089-0cf3cd906e36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MjcwNjYsIm5iZiI6MTcwOTkyNjc2NiwicGF0aCI6Ii80NTU4NTkzNy8zMTEzMzYxODQtMGFjMGRmN2UtMDFmMi00MjcwLWIwODktMGNmM2NkOTA2ZTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE5MzkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOWRkYjBlNmVhOGEyNTM4Zjg1ZDJiYjJiYmJjODFiYzFlMmIyYmZmNzljN2ZmNTBmOTFhNzE2YzIzMmQ0NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.urdOhc69zpg2T3EfGfGnh0qtxIXxUQ0iH4410T63hlQ">

Curious - did you directly bake this into Zed, or is this an extension?

**Comment by prabh8331** [comment]
Hello, Today I have downloaded on linux, I was a VS code user and i am trying to find better alternative, in vs code there was one extension which i used  a lot called TODO tree, where my all todo, fixme, bug are shown in single place, is there anything similer to that here?

**Comment by kohltastrophe** [comment]
Just checking in to see if there's been any progress or updates on extension capabilities that might support this feature? This is one of the few remaining features impacting my decision to fully adopt Zed, and I'm really eager to see it implemented.

Any insights or timelines from the extension team would be greatly appreciated by those of us who have been patiently waiting for this issue to be resolved. If there are ways we could contribute or assist in bringing this feature to fruition, please let us know.

**Comment by FrancoLab** [comment]
This would be awesome. Switched to Zed from NVim and would love this feature / extension

**Comment by TheKamboy** [comment]
this would be a nice feature to have

**Comment by reslear** [comment]
Maybe someone has already made their own patch? please share it

**Comment by dogezen** [comment]
would like this as well

**Comment by aretrace** [comment]
I completely understand the initial notion that this seems to be better implemented as a plugin, **_BUT_** I do think a integrated comment tag system (with configurable and sensible defaults) would really set zed apart (e.g., using TODO tree in VS Code is supper convenient). Think of it as a nice addition of the 'Standard Library' of zed.

**Comment by krstp** [comment]
Well.. one thing should be mentioned I do not think it is exactly possible to get it as a plugin. I did try to dab at it, but no success.

TBH, whatever I was trying to do was related to line wrapping, which I think would have the implementation logic somewhat similar.

I was able to create a dummy extension template and install it, but any further changes always took me to the editor level modification, which I need to admit was a notch beyond my comprehension. To be more precise, I do not think plugins level let you access editor level crate for mods 🤔  

Checking further the documentation on extensions, I think they are limited to: themes, languages, slash commands (https://zed.dev/docs/extensions/developing-extensions).

Maybe I am misinterpreting something, but AFAIK the modification will need to happen in the base code.

P.S.: If there is a way to do it at the plugin level, I would be happy to get some guidance from the devs and do it. 

BTW: I did try to use zed-chat, seeking guidance, but I did not get any answers... :(

**Comment by Cluster444** [comment]
This should absolutely be in the core zed product. Sorry, but saying this is best as a plugin is not understanding the product you're even building.

I don't want to have to install dozens of dependencies to get basic programming features I use every day.

**Comment by kamerado** [comment]
> This should absolutely be in the core zed product. Sorry, but saying this is best as a plugin is not understanding the product you're even building.
> 
> 
> 
> I don't want to have to install dozens of dependencies to get basic programming features I use every day.

I absolutely agree. at this point it makes more sense to just use neovim if you want customization

**Comment by Moshyfawn** [comment]
You're forgetting the fact that extensions can be shipped with the editor by default.

**Comment by andreacfromtheapp** [comment]
+1 please 

I used vi/vim/neovim and their distro + manual config; Atom, VS Code, Sublime and every editor on earth; lastly I am coming from Emacs to Zed and I really miss this https://docs.doomemacs.org/v21.12/modules/ui/hl-todo/

I would contribute this extension but I'm a Rust beginner still and reading comments here it seems that at the moment this would require some Zed changes.

**Comment by praktiskt** [comment]
I got the same idea as berkus above and got an hour to play with this today.

I used:
* Tree sitter: https://github.com/stsewd/tree-sitter-comment
* `highlights.scm` from [nvim-treesitter for comment](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/comment/highlights.scm)

I wrote a crude plugin that is able to mark things like `TODO`, `WIP` as a [Language Extension (follow the guide)](https://zed.dev/docs/extensions/languages) meaning TODO-highlighting had to be selected as a language (`Ctrl+K M` -> `TODO`) for the buffer, meaning _all other syntax highlighting for the language disappeared_ (ugh).

I am not sure it's possible to write an extension for this **and** maintain any languages' original highlighting. I only spent 10 minutes playing around with `injections.scm` but was only ever able to hard-set the language I wanted the original syntax highlighting for (kind of, and mostly incompletely). Would love to get some guidance whether this is possible or not and/or a nudge in the right direction. If there's another extension doing something similar that would work too.

Dropping the work I did below in case someone else wants to take a stab at it. It's nowhere near usable in its current state.

```toml
# extension.toml
# ...
[grammars.comment]
repository = "https://github.com/stsewd/tree-sitter-comment"
commit = "3555706cef8b98d3e4c7379d7260548ff03ad363
```

```toml
# languages/comment/config.toml
name = "TODO"
grammar = "comment"
path_suffixes = []
line_comments = ["# ", "// ", "/// ", "-- "]
```

```scm
; languages/comment/highlights.scm
; Copy from here: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/comment/highlights.scm
...
```

**Comment by griffi-gh** [comment]
Actually, ideally we would have sth like TODO Tree from vscode (highlight + a sidebar tab to view all TODOs)

**Comment by nnra6864** [comment]
I heavily rely on these comments, would be nice to see this feature implemented.

**Comment by cloudUser98** [comment]
Zed supports [multi language documents!!!](https://zed.dev/blog/syntax-aware-editing#multi-language-documents). The problem i see is that this type of language injection needs to be specified in the already existing extensions. If we want this to work with tree sitter (tbh that sounds really cool) we need a way to set a global grammar for any type of document.

**Comment by unkindypie** [comment]
Bumping this, must have feature

**Comment by autibequi** [comment]
Bumping too
the other option to that is to track small things to change on Jira that will be forgotten

At least like that random smarter college can check it later while doing other tasks.

Maybe an aggregated collaborate to-do to-fix (to-any??) list would be a great add to collaboration tab to async spread information about code details.

**Comment by anphir** [comment]
### TODO Tree

Using Zed's project search combined with the outline panel works surprisingly well for me.
The center view displays a multi-buffer list of TODOs etc. for quick editing and the outline panel displays a terse tree view.

### Comment Highlighting

After quite some tree-sitting, query-scheming and tinkering with my Zed installation, I have an extension enabling highlighting for comments by means of tree-sitter queries ([repository](https://github.com/anphir/zed-comment.git), pull request [#2865](https://github.com/zed-industries/extensions/pull/2865)).

As others have already pointed out, that's not all that needs to be done.
At least with current Zed, you can't just 'switch on' a language extension's comment highlighting from the outside.
They need to implement 'language injection' as e.g. done to highlight JavaScript embedded in HTML sources.

I have installed a few languages in form of development extensions with the required injection implemented.
For these the needed changes were pretty small.

If anyone wants to try this approach, the [repository](https://github.com/anphir/zed-comment.git) with the extension contains a guide.

### UPDATE October 2025

Please note that Zed devs preferred to merge PR #3393 instead of #2865.

**Comment by DZinin-Bro** [comment]
Nice source of inspiration https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree

**Comment by runejac** [comment]
Bumping this, must have

**Comment by puhtaytow** [comment]
This and the bookmarks issue, makes me think that maybe extensions API should be extended. Otherwise, we would have to wait years for developers to bring small functionality like these 😕

**Comment by Jala015** [comment]
Hi, i have created a [task](https://zed.dev/docs/tasks) that uses [ripgrep (rg)](https://github.com/BurntSushi/ripgrep) to list the todos on a new terminal, with file links to the respective files:

```
 {
    "label": "List TODO/FIXME",
    "command": "rg",
    "args": ["--hyperlink-format=file://{path}", "-e TODO", "-e FIXME"],
    "cwd": "${ZED_WORKTREE_ROOT}",
    "use_new_terminal": true,
    "allow_concurrent_runs": false,
    "reveal": "always",
    "hide": "never",
    "show_summary": true,
    "show_command": true,
    "reveal_target": "center"
  }
```

**Comment by samuelreddotcom** [comment]
@Jala015 this was so helpful.

**Comment by Dima-369** [comment]
If tasks had the ability to display a real Zed multi buffer based on `rg` output (on exit code 0), or any other binary by only allowing a strict stdout input, this could be implemented in a very nice way.

**Comment by HeraldOD** [comment]
> Hi, i have created a [task](https://zed.dev/docs/tasks) that uses [ripgrep (rg)](https://github.com/BurntSushi/ripgrep) to list the todos on a new terminal, with file links to the respective files (...)

```
{
    "label": "List TODOs",
    "command": "rg",
    "args": [
        "--hyperlink-format=file://{path}:{line}",
        "-e TODO",
        "-e FIXME",
        "-e HACK"
    ],
    "cwd": "${ZED_WORKTREE_ROOT}",
    "use_new_terminal": true,
    "allow_concurrent_runs": false,
    "reveal": "always",
    "hide": "never",
    "show_summary": false,
    "show_command": false,
    "reveal_target": "dock"
}
```

Changing the hyperlink format to "--hyperlink-format=file://{path}:{line}" makes the numbers clickable, to go directly to the line

**Comment by AirCode2560** [comment]
This needs to happen to make it fully featured, personally i like the regex oriented style so i can define my own custom tag formats...

**Comment by untimated** [comment]
so any solution yet ?

**Comment by boozook** [comment]
@untimated 

> so any solution yet ?

Nope, unfortunately.

**Comment by onetrev** [comment]
It's early days, but this is now possible via the [Zed Comment](https://github.com/thedadams/zed-comment) extension. There is more active discussion in [another issue](https://github.com/zed-industries/zed/issues/11895), so maybe this issue should be closed/merged with that one?

**Comment by berkus** [comment]
Looks like this can be closed at all, for the "highlighting" part indeed works! ❤️

**Comment by brokenthorn** [comment]
> Personally believe this should be left to a Plugin

https://crates.io/crates/zed-todo-tree

EDIT: I don't understand why the down-votes. It was just a suggestion for a working plugin that I personally use that might also help those looking for an alternative.

**Comment by magikmw** [comment]
> > Personally believe this should be left to a Plugin
> 
> https://crates.io/crates/zed-todo-tree

This crate's repo is 404.

**Comment by bubnov** [comment]
TODO/etc. tags highlighting is a minor issue here, imo. Much more useful is to see all todos in a `Project Diagnostic` along with errors and warnings. I used to this in VSCode and this is what I'm missing in Zed.

**Comment by brokenthorn** [comment]
Back when I was using VSCode, this plugin was unbeatable: https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree

It uses ripgrep (`rg`) under the hood so it's super fast. It's also quite configurable (you can define your own tags (so you could highlight `todo!` macros) and customize a lot of things related to rendering tags, and how the sidebar section of the plugin works (tree/list view, etc.) as well as how the statusbar summaries render, the tooltips, etc.).

Hopefully it can be a source of inspiration for future development.

**Comment by zargony** [comment]
[Zed Comment](https://github.com/thedadams/zed-comment) is a great extension for the current situation. Great job on integrating into all the different languages!

But it sometimes feels like a workaround. Because it only matches keywords in comments of known languages it sometimes catches me out. I’m tempted to leave XXX in code or markup to indicate WIP but it doesn’t work that way. I’m trying to adjust my habits to add comments instead but it’s tedious, especially with YAML and JSON.

Customization is also a bit tricky. Theme overrides are tedious to maintain with multiple themes. Using constant/string/keyword/property for categorization feels like a (temporary?) hack. I personally wouldn’t group XXX and INFO together as they mean very different urgencies to me. While I’m trying to adjust my habits here too, it's tedious sometimes.

Zed Comment is quite sophisticated and cool, but I'd actually really appreciate something simpler. E.g. a "simple" regex search over text/lines that highlights each occurrence/line would be much more appealing.

**Comment by boozook** [comment]
@bubnov,
> TODO/etc. tags highlighting is a minor issue here, imo. Much more useful is to see all todos in a `Project Diagnostic` along with errors and warnings. I used to this in VSCode and this is what I'm missing in Zed.

I've just created rules for [`ast-grep`](https://ast-grep.github.io) for some langs such as rust and toml. That way I can open terminal-pane with a neat list of in-comment markers, [like it is above ☝🏻][term-comment], and bind it to hotkey; but also there is a cool way to get it in a `Project Diagnostic` as you wish, using [`ast-grep-ls`][ls] _(Language Server)_.

<details><summary>My rules:</summary>

* `todo.rs.yml`:
```yaml
id: important marker
language: Rust
severity: warning # but `error` could be better
message: "$MSG"
note: Fix it or resolve somehow
rule:
  regex: ((?:FIXME|XXX|BUG|FUCK)[:!](?:\s*|\s+(.*)))\s*
  pattern: $COMMENT
  matches: any-comment

transform:
  MSG:
    replace:
      source: $COMMENT
      replace: (?:.|\s)*?.*(FIXME|XXX|BUG|FUCK)[:!](?:\s+(.+?))\s*(?:\n|\*\/|$)
      by: "$1: $2\n"

---
id: dev marker
language: Rust
severity: warning
note: Just do it!
message: "$MSG"
rule:
  regex: ((?:TODO|DEV)[:!](?:\s*|\s+(.*)))\s*
  pattern: $COMMENT
  matches: any-comment

transform:
  MSG:
    replace:
      source: $COMMENT
      replace: (?:.|\s)*?.*(TODO|DEV)[:!](?:\s+(.+?))\s*(?:\n|\*\/|$)
      by: "$1: $2\n"

---
id: info marker
language: Rust
severity: info # or `hint` may be
message: "$MSG"
rule:
  regex: ((?:PLAN|NOTE|HACK)[:!](?:\s*|\s+(.*)))\s*
  pattern: $COMMENT
  matches: any-comment

transform:
  MSG:
    replace:
      source: $COMMENT
      replace: (?:.|\s)*?.*(PLAN|NOTE|HACK)[:!](?:\s+(.+?))\s*(?:\n|\*\/|$)
      by: "$1: $2\n"
```
* `todo.toml.yml`:
```yaml
id: comment marker
language: toml
severity: warning
message: "$MSG"
note: Fix it or resolve somehow

rule:
  regex: ((?:TODO|DEV|FIXME|XXX|BUG|FUCK|PLAN|NOTE|HACK)[:!](?:\s*|\s+(.*)))\s*
  pattern: $COMMENT
  kind: comment

transform:
  MSG:
    replace:
      source: $COMMENT
      replace: (?:.|\s)*?\b(TODO|DEV|FIXME|XXX|BUG|FUCK|PLAN|NOTE|HACK)[:!](?:\s+(.+?))\s*$
      by: "$1: $2\n"
```
* `utils/rs.any-comment.yml `:
```yaml
id: any-comment
language: Rust
rule:
  any:
    - kind: doc_comment
    - kind: block_comment, line_comment
      not:
        has:
          pattern: $_
```

</details>



[term-comment]: https://github.com/zed-industries/extensions/issues/523#issuecomment-3325210094
[ls]: https://github.com/mathieulj/ast-grep-zed
